<?php

use Illuminate\Database\Seeder;
use App\City;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert(['id'=>1, 'name'=> 'Argentina', 'demonym'=> 'argentino']);
		DB::table('countries')->insert(['id'=>2, 'name'=> 'Birmania', 'demonym'=> 'birmano']);
		DB::table('countries')->insert(['id'=>3, 'name'=> 'Chipre del Norte', 'demonym'=> 'norchipriota']);
		DB::table('countries')->insert(['id'=>4, 'name'=> 'Somalilandia', 'demonym'=> 'somalilandés']);
		DB::table('countries')->insert(['id'=>5, 'name'=> 'Sint Maarten', 'demonym'=> 'sanmartitense']);
		DB::table('countries')->insert(['id'=>6, 'name'=> 'Nueva Rusia', 'demonym'=> 'neorruso']);
		DB::table('countries')->insert(['id'=>7, 'name'=> 'Abjasia', 'demonym'=> 'abjasio']);
		DB::table('countries')->insert(['id'=>8, 'name'=> 'Zimbabue', 'demonym'=> 'zimbabuense']);
		DB::table('countries')->insert(['id'=>9, 'name'=> 'Zambia', 'demonym'=> 'zambiano']);
		DB::table('countries')->insert(['id'=>10, 'name'=> 'Yibuti', 'demonym'=> 'yibutiano']);
		DB::table('countries')->insert(['id'=>11, 'name'=> 'Yemen', 'demonym'=> 'yemení']);
		DB::table('countries')->insert(['id'=>12, 'name'=> 'Wallis y Futuna', 'demonym'=> 'walisiano']);
		DB::table('countries')->insert(['id'=>13, 'name'=> 'Vietnam', 'demonym'=> 'vietnamita']);
		DB::table('countries')->insert(['id'=>14, 'name'=> 'Venezuela', 'demonym'=> 'venezolano']);
		DB::table('countries')->insert(['id'=>15, 'name'=> 'Vanuatu', 'demonym'=> 'vanuatuense']);
		DB::table('countries')->insert(['id'=>16, 'name'=> 'Uzbekistán', 'demonym'=> 'uzbeko']);
		DB::table('countries')->insert(['id'=>17, 'name'=> 'Uruguay', 'demonym'=> 'uruguayo']);
		DB::table('countries')->insert(['id'=>18, 'name'=> 'Uganda', 'demonym'=> 'ugandés']);
		DB::table('countries')->insert(['id'=>19, 'name'=> 'Ucrania', 'demonym'=> 'ucraniano']);
		DB::table('countries')->insert(['id'=>20, 'name'=> 'Tuvalu', 'demonym'=> 'tuvaluano']);
		DB::table('countries')->insert(['id'=>21, 'name'=> 'Turquía', 'demonym'=> 'turco']);
		DB::table('countries')->insert(['id'=>22, 'name'=> 'Turkmenistán', 'demonym'=> 'turcomano o turkmeno']);
		DB::table('countries')->insert(['id'=>23, 'name'=> 'Túnez', 'demonym'=> 'tunecino']);
		DB::table('countries')->insert(['id'=>24, 'name'=> 'Trinidad y Tobago', 'demonym'=> 'trinitense']);
		DB::table('countries')->insert(['id'=>25, 'name'=> 'Transnistria', 'demonym'=> 'transnistrio']);
		DB::table('countries')->insert(['id'=>26, 'name'=> 'Tonga', 'demonym'=> 'tongano']);
		DB::table('countries')->insert(['id'=>27, 'name'=> 'Tokelau', 'demonym'=> 'tokelauense']);
		DB::table('countries')->insert(['id'=>28, 'name'=> 'Togo', 'demonym'=> 'togolés']);
		DB::table('countries')->insert(['id'=>29, 'name'=> 'Timor Oriental', 'demonym'=> 'timorense']);
		DB::table('countries')->insert(['id'=>30, 'name'=> 'Tayikistán', 'demonym'=> 'tayiko']);
		DB::table('countries')->insert(['id'=>31, 'name'=> 'Tanzania', 'demonym'=> 'tanzano']);
		DB::table('countries')->insert(['id'=>32, 'name'=> 'República de China', 'demonym'=> 'taiwanés']);
		DB::table('countries')->insert(['id'=>33, 'name'=> 'Tailandia', 'demonym'=> 'tailandés']);
		DB::table('countries')->insert(['id'=>34, 'name'=> 'Svalbard', 'demonym'=> 'svalbarense']);
		DB::table('countries')->insert(['id'=>35, 'name'=> 'Surinam', 'demonym'=> 'surinamés']);
		DB::table('countries')->insert(['id'=>36, 'name'=> 'Suiza', 'demonym'=> 'suizo']);
		DB::table('countries')->insert(['id'=>37, 'name'=> 'Suecia', 'demonym'=> 'sueco']);
		DB::table('countries')->insert(['id'=>38, 'name'=> 'Sudán', 'demonym'=> 'sudanés']);
		DB::table('countries')->insert(['id'=>39, 'name'=> 'Sudán del Sur', 'demonym'=> 'sursudanés']);
		DB::table('countries')->insert(['id'=>40, 'name'=> 'Sudáfrica', 'demonym'=> 'sudafricano']);
		DB::table('countries')->insert(['id'=>41, 'name'=> 'Suazilandia', 'demonym'=> 'suazi']);
		DB::table('countries')->insert(['id'=>42, 'name'=> 'Sri Lanka', 'demonym'=> 'ceilanés o ceilandés o esrilanqués']);
		DB::table('countries')->insert(['id'=>43, 'name'=> 'Somalia', 'demonym'=> 'somalí']);
		DB::table('countries')->insert(['id'=>44, 'name'=> 'Siria', 'demonym'=> 'sirio']);
		DB::table('countries')->insert(['id'=>45, 'name'=> 'Singapur', 'demonym'=> 'singapurense']);
		DB::table('countries')->insert(['id'=>46, 'name'=> 'Sierra Leona', 'demonym'=> 'sierraleonés']);
		DB::table('countries')->insert(['id'=>47, 'name'=> 'Seychelles', 'demonym'=> 'seychellense']);
		DB::table('countries')->insert(['id'=>48, 'name'=> 'Serbia', 'demonym'=> 'serbio']);
		DB::table('countries')->insert(['id'=>49, 'name'=> 'Senegal', 'demonym'=> 'senegalés']);
		DB::table('countries')->insert(['id'=>50, 'name'=> 'Santo Tomé y Príncipe', 'demonym'=> 'santotomense']);
		DB::table('countries')->insert(['id'=>51, 'name'=> 'Santa Lucía', 'demonym'=> 'santalucense']);
		DB::table('countries')->insert(['id'=>52, 'name'=> 'Santa Elena, Ascensión y Tristán de Acuña', 'demonym'=> 'santaheleno']);
		DB::table('countries')->insert(['id'=>53, 'name'=> 'San Vicente y las Granadinas', 'demonym'=> 'sanvicentino']);
		DB::table('countries')->insert(['id'=>54, 'name'=> 'San Pedro y Miquelón', 'demonym'=> 'sampedrino']);
		DB::table('countries')->insert(['id'=>55, 'name'=> 'San Martín', 'demonym'=> 'sanmartitense']);
		DB::table('countries')->insert(['id'=>56, 'name'=> 'San Marino', 'demonym'=> 'sanmarinense']);
		DB::table('countries')->insert(['id'=>57, 'name'=> 'San Cristóbal y Nieves', 'demonym'=> 'sancristobaleño']);
		DB::table('countries')->insert(['id'=>58, 'name'=> 'San Bartolomé', 'demonym'=> 'sambartolomeano']);
		DB::table('countries')->insert(['id'=>59, 'name'=> 'Samoa', 'demonym'=> 'samoano']);
		DB::table('countries')->insert(['id'=>60, 'name'=> 'Samoa Americana', 'demonym'=> 'samoamericano']);
		DB::table('countries')->insert(['id'=>61, 'name'=> 'Sahara Occidental', 'demonym'=> 'saharaui']);
		DB::table('countries')->insert(['id'=>62, 'name'=> 'Rusia', 'demonym'=> 'ruso']);
		DB::table('countries')->insert(['id'=>63, 'name'=> 'Rumania', 'demonym'=> 'rumano']);
		DB::table('countries')->insert(['id'=>64, 'name'=> 'Ruanda', 'demonym'=> 'ruandés']);
		DB::table('countries')->insert(['id'=>65, 'name'=> 'China', 'demonym'=> 'chino']);
		DB::table('countries')->insert(['id'=>66, 'name'=> 'República Dominicana', 'demonym'=> 'dominicano']);
		DB::table('countries')->insert(['id'=>67, 'name'=> 'República Democrática del Congo', 'demonym'=> 'congoleño o congolés']);
		DB::table('countries')->insert(['id'=>68, 'name'=> 'República del Congo', 'demonym'=> 'congoleño o congolés']);
		DB::table('countries')->insert(['id'=>69, 'name'=> 'República de Macedonia', 'demonym'=> 'macedonio']);
		DB::table('countries')->insert(['id'=>70, 'name'=> 'República Checa', 'demonym'=> 'checo']);
		DB::table('countries')->insert(['id'=>71, 'name'=> 'República Centroafricana', 'demonym'=> 'centroafricano']);
		DB::table('countries')->insert(['id'=>72, 'name'=> 'Reino Unido', 'demonym'=> 'británico']);
		DB::table('countries')->insert(['id'=>73, 'name'=> 'Puerto Rico', 'demonym'=> 'puertorriqueño o portorriqueño']);
		DB::table('countries')->insert(['id'=>74, 'name'=> 'Portugal', 'demonym'=> 'portugués']);
		DB::table('countries')->insert(['id'=>75, 'name'=> 'Polonia', 'demonym'=> 'polaco']);
		DB::table('countries')->insert(['id'=>76, 'name'=> 'Polinesia Francesa', 'demonym'=> 'francopolinesio']);
		DB::table('countries')->insert(['id'=>77, 'name'=> 'Perú', 'demonym'=> 'peruano']);
		DB::table('countries')->insert(['id'=>78, 'name'=> 'Paraguay', 'demonym'=> 'paraguayo']);
		DB::table('countries')->insert(['id'=>79, 'name'=> 'Papúa Nueva Guinea', 'demonym'=> 'papú o papúa']);
		DB::table('countries')->insert(['id'=>80, 'name'=> 'Panamá', 'demonym'=> 'panameño']);
		DB::table('countries')->insert(['id'=>81, 'name'=> 'Palestina', 'demonym'=> 'palestino']);
		DB::table('countries')->insert(['id'=>82, 'name'=> 'Palaos', 'demonym'=> 'palauano']);
		DB::table('countries')->insert(['id'=>83, 'name'=> 'Pakistán', 'demonym'=> 'pakistaní']);
		DB::table('countries')->insert(['id'=>84, 'name'=> 'Países Bajos', 'demonym'=> 'neerlandés']);
		DB::table('countries')->insert(['id'=>85, 'name'=> 'Osetia del Sur', 'demonym'=> 'surosetio']);
		DB::table('countries')->insert(['id'=>86, 'name'=> 'Omán', 'demonym'=> 'omaní']);
		DB::table('countries')->insert(['id'=>87, 'name'=> 'Nueva Zelanda', 'demonym'=> 'neozelandés']);
		DB::table('countries')->insert(['id'=>88, 'name'=> 'Nueva Caledonia', 'demonym'=> 'neocaledonio']);
		DB::table('countries')->insert(['id'=>89, 'name'=> 'Noruega', 'demonym'=> 'noruego']);
		DB::table('countries')->insert(['id'=>90, 'name'=> 'Niue', 'demonym'=> 'niueño']);
		DB::table('countries')->insert(['id'=>91, 'name'=> 'Níger', 'demonym'=> 'nigerino']);
		DB::table('countries')->insert(['id'=>92, 'name'=> 'Nigeria', 'demonym'=> 'nigeriano']);
		DB::table('countries')->insert(['id'=>93, 'name'=> 'Nicaragua', 'demonym'=> 'nicaragüense']);
		DB::table('countries')->insert(['id'=>94, 'name'=> 'Nepal', 'demonym'=> 'nepalés o nepalí']);
		DB::table('countries')->insert(['id'=>95, 'name'=> 'Nauru', 'demonym'=> 'nauruano']);
		DB::table('countries')->insert(['id'=>96, 'name'=> 'Namibia', 'demonym'=> 'namibio']);
		DB::table('countries')->insert(['id'=>97, 'name'=> 'Mozambique', 'demonym'=> 'mozambiqueño']);
		DB::table('countries')->insert(['id'=>98, 'name'=> 'Montserrat', 'demonym'=> 'monserratino']);
		DB::table('countries')->insert(['id'=>99, 'name'=> 'Montenegro', 'demonym'=> 'montenegrino']);
		DB::table('countries')->insert(['id'=>100, 'name'=> 'Mongolia', 'demonym'=> 'mongol']);
		DB::table('countries')->insert(['id'=>101, 'name'=> 'Mónaco', 'demonym'=> 'monegasco']);
		DB::table('countries')->insert(['id'=>102, 'name'=> 'Moldavia', 'demonym'=> 'moldavo']);
		DB::table('countries')->insert(['id'=>103, 'name'=> 'México', 'demonym'=> 'mexicano o mejicano']);
		DB::table('countries')->insert(['id'=>104, 'name'=> 'Mauritania', 'demonym'=> 'mauritano']);
		DB::table('countries')->insert(['id'=>105, 'name'=> 'Mauricio', 'demonym'=> 'mauriciano']);
		DB::table('countries')->insert(['id'=>106, 'name'=> 'Marruecos', 'demonym'=> 'marroquí']);
		DB::table('countries')->insert(['id'=>107, 'name'=> 'Malta', 'demonym'=> 'maltés']);
		DB::table('countries')->insert(['id'=>108, 'name'=> 'Malí', 'demonym'=> 'maliense']);
		DB::table('countries')->insert(['id'=>109, 'name'=> 'Maldivas', 'demonym'=> 'maldivo']);
		DB::table('countries')->insert(['id'=>110, 'name'=> 'Malaui', 'demonym'=> 'malauí']);
		DB::table('countries')->insert(['id'=>111, 'name'=> 'Malasia', 'demonym'=> 'malasio']);
		DB::table('countries')->insert(['id'=>112, 'name'=> 'Madagascar', 'demonym'=> 'malgache']);
		DB::table('countries')->insert(['id'=>113, 'name'=> 'Macao', 'demonym'=> 'macaense']);
		DB::table('countries')->insert(['id'=>114, 'name'=> 'Luxemburgo', 'demonym'=> 'luxemburgués']);
		DB::table('countries')->insert(['id'=>115, 'name'=> 'Lituania', 'demonym'=> 'lituano']);
		DB::table('countries')->insert(['id'=>116, 'name'=> 'Liechtenstein', 'demonym'=> 'liechtensteiniano']);
		DB::table('countries')->insert(['id'=>117, 'name'=> 'Libia', 'demonym'=> 'libio']);
		DB::table('countries')->insert(['id'=>118, 'name'=> 'Liberia', 'demonym'=> 'liberiano']);
		DB::table('countries')->insert(['id'=>119, 'name'=> 'Líbano', 'demonym'=> 'libanés']);
		DB::table('countries')->insert(['id'=>120, 'name'=> 'Letonia', 'demonym'=> 'letón']);
		DB::table('countries')->insert(['id'=>121, 'name'=> 'Lesoto', 'demonym'=> 'lesotense']);
		DB::table('countries')->insert(['id'=>122, 'name'=> 'Laos', 'demonym'=> 'laosiano']);
		DB::table('countries')->insert(['id'=>123, 'name'=> 'República de Nagorno Karabaj', 'demonym'=> 'karabají']);
		DB::table('countries')->insert(['id'=>124, 'name'=> 'Kuwait', 'demonym'=> 'kuwaití']);
		DB::table('countries')->insert(['id'=>125, 'name'=> 'Kosovo', 'demonym'=> 'kosovar']);
		DB::table('countries')->insert(['id'=>126, 'name'=> 'Kiribati', 'demonym'=> 'kiribatiano']);
		DB::table('countries')->insert(['id'=>127, 'name'=> 'Kirguistán', 'demonym'=> 'kirguís o kirguiso']);
		DB::table('countries')->insert(['id'=>128, 'name'=> 'Kenia', 'demonym'=> 'keniano']);
		DB::table('countries')->insert(['id'=>129, 'name'=> 'Kazajistán', 'demonym'=> 'kazajo']);
		DB::table('countries')->insert(['id'=>130, 'name'=> 'Jordania', 'demonym'=> 'jordano']);
		DB::table('countries')->insert(['id'=>131, 'name'=> 'Jersey', 'demonym'=> 'jerseyés']);
		DB::table('countries')->insert(['id'=>132, 'name'=> 'Japón', 'demonym'=> 'japonés']);
		DB::table('countries')->insert(['id'=>133, 'name'=> 'Jamaica', 'demonym'=> 'jamaicano o jamaiquino']);
		DB::table('countries')->insert(['id'=>134, 'name'=> 'Italia', 'demonym'=> 'italiano']);
		DB::table('countries')->insert(['id'=>135, 'name'=> 'Israel', 'demonym'=> 'israelí']);
		DB::table('countries')->insert(['id'=>136, 'name'=> 'Islas Vírgenes de los Estados Unidos', 'demonym'=> 'virgenense']);
		DB::table('countries')->insert(['id'=>137, 'name'=> 'Islas Vírgenes Británicas', 'demonym'=> 'virgenense']);
		DB::table('countries')->insert(['id'=>138, 'name'=> 'Islas Turcas y Caicos', 'demonym'=> 'turcocaiqueño']);
		DB::table('countries')->insert(['id'=>139, 'name'=> 'Islas Salomón', 'demonym'=> 'salomonense']);
		DB::table('countries')->insert(['id'=>140, 'name'=> 'Islas Pitcairn', 'demonym'=> 'pitcairnés']);
		DB::table('countries')->insert(['id'=>141, 'name'=> 'Islas Marshall', 'demonym'=> 'marshalés']);
		DB::table('countries')->insert(['id'=>142, 'name'=> 'Islas Marianas del Norte', 'demonym'=> 'chamorro']);
		DB::table('countries')->insert(['id'=>143, 'name'=> 'Islas Malvinas', 'demonym'=> 'malvinense']);
		DB::table('countries')->insert(['id'=>144, 'name'=> 'Islas Feroe', 'demonym'=> 'feroés']);
		DB::table('countries')->insert(['id'=>145, 'name'=> 'Islas Cook', 'demonym'=> 'cookiano']);
		DB::table('countries')->insert(['id'=>146, 'name'=> 'Islas Cocos', 'demonym'=> 'cocano']);
		DB::table('countries')->insert(['id'=>147, 'name'=> 'Islas Caimán', 'demonym'=> 'caimanés']);
		DB::table('countries')->insert(['id'=>148, 'name'=> 'Islandia', 'demonym'=> 'islandés']);
		DB::table('countries')->insert(['id'=>149, 'name'=> 'Isla Norfolk', 'demonym'=> 'norfolkense']);
		DB::table('countries')->insert(['id'=>150, 'name'=> 'Isla de Navidad', 'demonym'=> 'navideño']);
		DB::table('countries')->insert(['id'=>151, 'name'=> 'Isla de Man', 'demonym'=> 'manés']);
		DB::table('countries')->insert(['id'=>152, 'name'=> 'Irlanda', 'demonym'=> 'irlandés']);
		DB::table('countries')->insert(['id'=>153, 'name'=> 'Irán', 'demonym'=> 'iraní']);
		DB::table('countries')->insert(['id'=>154, 'name'=> 'Irak', 'demonym'=> 'iraquí']);
		DB::table('countries')->insert(['id'=>155, 'name'=> 'Indonesia', 'demonym'=> 'indonesio']);
		DB::table('countries')->insert(['id'=>156, 'name'=> 'India', 'demonym'=> 'indio']);
		DB::table('countries')->insert(['id'=>157, 'name'=> 'Hungría', 'demonym'=> 'húngaro']);
		DB::table('countries')->insert(['id'=>158, 'name'=> 'Hong Kong', 'demonym'=> 'hongkonés']);
		DB::table('countries')->insert(['id'=>159, 'name'=> 'Honduras', 'demonym'=> 'hondureño']);
		DB::table('countries')->insert(['id'=>160, 'name'=> 'Haití', 'demonym'=> 'haitiano']);
		DB::table('countries')->insert(['id'=>161, 'name'=> 'Guyana', 'demonym'=> 'guyanés']);
		DB::table('countries')->insert(['id'=>162, 'name'=> 'Guinea', 'demonym'=> 'guineano o guineo']);
		DB::table('countries')->insert(['id'=>163, 'name'=> 'Guinea-Bisáu', 'demonym'=> 'guineano o guineo o bisauguineano']);
		DB::table('countries')->insert(['id'=>164, 'name'=> 'Guinea Ecuatorial', 'demonym'=> 'ecuatoguineano']);
		DB::table('countries')->insert(['id'=>165, 'name'=> 'Guernsey', 'demonym'=> 'guerneseyés o guernesiano']);
		DB::table('countries')->insert(['id'=>166, 'name'=> 'Guatemala', 'demonym'=> 'guatemalteco o guatemalense']);
		DB::table('countries')->insert(['id'=>167, 'name'=> 'Guam', 'demonym'=> 'guameño']);
		DB::table('countries')->insert(['id'=>168, 'name'=> 'Groenlandia', 'demonym'=> 'groenlandés']);
		DB::table('countries')->insert(['id'=>169, 'name'=> 'Grecia', 'demonym'=> 'griego']);
		DB::table('countries')->insert(['id'=>170, 'name'=> 'Granada', 'demonym'=> 'granadino']);
		DB::table('countries')->insert(['id'=>171, 'name'=> 'Gibraltar', 'demonym'=> 'gibraltareño']);
		DB::table('countries')->insert(['id'=>172, 'name'=> 'Ghana', 'demonym'=> 'ghanés']);
		DB::table('countries')->insert(['id'=>173, 'name'=> 'Georgia', 'demonym'=> 'georgiano']);
		DB::table('countries')->insert(['id'=>174, 'name'=> 'Gambia', 'demonym'=> 'gambiano']);
		DB::table('countries')->insert(['id'=>175, 'name'=> 'Gabón', 'demonym'=> 'gabonés']);
		DB::table('countries')->insert(['id'=>176, 'name'=> 'Francia', 'demonym'=> 'francés']);
		DB::table('countries')->insert(['id'=>177, 'name'=> 'Fiyi', 'demonym'=> 'fiyiano']);
		DB::table('countries')->insert(['id'=>178, 'name'=> 'Finlandia', 'demonym'=> 'finlandés o finés']);
		DB::table('countries')->insert(['id'=>179, 'name'=> 'Filipinas', 'demonym'=> 'filipino']);
		DB::table('countries')->insert(['id'=>180, 'name'=> 'Etiopía', 'demonym'=> 'etíope']);
		DB::table('countries')->insert(['id'=>181, 'name'=> 'Estonia', 'demonym'=> 'estonio o estoniano']);
		DB::table('countries')->insert(['id'=>182, 'name'=> 'Estados Unidos', 'demonym'=> 'estadounidense o estadunidense']);
		DB::table('countries')->insert(['id'=>183, 'name'=> 'Estados Federados de Micronesia', 'demonym'=> 'micronesio']);
		DB::table('countries')->insert(['id'=>184, 'name'=> 'España', 'demonym'=> 'español']);
		DB::table('countries')->insert(['id'=>185, 'name'=> 'Eslovenia', 'demonym'=> 'esloveno']);
		DB::table('countries')->insert(['id'=>186, 'name'=> 'Eslovaquia', 'demonym'=> 'eslovaco']);
		DB::table('countries')->insert(['id'=>187, 'name'=> 'Eritrea', 'demonym'=> 'eritreo']);
		DB::table('countries')->insert(['id'=>188, 'name'=> 'Emiratos Árabes Unidos', 'demonym'=> 'emiratí']);
		DB::table('countries')->insert(['id'=>189, 'name'=> 'El Salvador', 'demonym'=> 'salvadoreño']);
		DB::table('countries')->insert(['id'=>190, 'name'=> 'Egipto', 'demonym'=> 'egipcio']);
		DB::table('countries')->insert(['id'=>191, 'name'=> 'Ecuador', 'demonym'=> 'ecuatoriano']);
		DB::table('countries')->insert(['id'=>192, 'name'=> 'Dominica', 'demonym'=> 'dominiqués']);
		DB::table('countries')->insert(['id'=>193, 'name'=> 'Dinamarca', 'demonym'=> 'danés o dinamarqués']);
		DB::table('countries')->insert(['id'=>194, 'name'=> 'Curazao', 'demonym'=> 'curazoleño']);
		DB::table('countries')->insert(['id'=>195, 'name'=> 'Cuba', 'demonym'=> 'cubano']);
		DB::table('countries')->insert(['id'=>196, 'name'=> 'Croacia', 'demonym'=> 'croata']);
		DB::table('countries')->insert(['id'=>197, 'name'=> 'Costa Rica', 'demonym'=> 'costarricense']);
		DB::table('countries')->insert(['id'=>198, 'name'=> 'Costa de Marfil', 'demonym'=> 'marfileño']);
		DB::table('countries')->insert(['id'=>199, 'name'=> 'Corea del Sur', 'demonym'=> 'surcoreano']);
		DB::table('countries')->insert(['id'=>200, 'name'=> 'Corea del Norte', 'demonym'=> 'norcoreano']);
		DB::table('countries')->insert(['id'=>201, 'name'=> 'Comoras', 'demonym'=> 'comorense']);
		DB::table('countries')->insert(['id'=>202, 'name'=> 'Colombia', 'demonym'=> 'colombiano']);
		DB::table('countries')->insert(['id'=>203, 'name'=> 'Ciudad del Vaticano', 'demonym'=> 'vaticano']);
		DB::table('countries')->insert(['id'=>204, 'name'=> 'Chipre', 'demonym'=> 'chipriota']);
		DB::table('countries')->insert(['id'=>205, 'name'=> 'Chile', 'demonym'=> 'chileno']);
		DB::table('countries')->insert(['id'=>206, 'name'=> 'Chad', 'demonym'=> 'chadiano']);
		DB::table('countries')->insert(['id'=>207, 'name'=> 'Catar', 'demonym'=> 'catarí']);
		DB::table('countries')->insert(['id'=>208, 'name'=> 'Canadá', 'demonym'=> 'canadiense']);
		DB::table('countries')->insert(['id'=>209, 'name'=> 'Camerún', 'demonym'=> 'camerunés']);
		DB::table('countries')->insert(['id'=>210, 'name'=> 'Camboya', 'demonym'=> 'camboyano']);
		DB::table('countries')->insert(['id'=>211, 'name'=> 'Cabo Verde', 'demonym'=> 'caboverdiano']);
		DB::table('countries')->insert(['id'=>212, 'name'=> 'Bután', 'demonym'=> 'butanés']);
		DB::table('countries')->insert(['id'=>213, 'name'=> 'Burundi', 'demonym'=> 'burundés']);
		DB::table('countries')->insert(['id'=>214, 'name'=> 'Burkina Faso', 'demonym'=> 'burkinés']);
		DB::table('countries')->insert(['id'=>215, 'name'=> 'Bulgaria', 'demonym'=> 'búlgaro']);
		DB::table('countries')->insert(['id'=>216, 'name'=> 'Brunéi', 'demonym'=> 'bruneano']);
		DB::table('countries')->insert(['id'=>217, 'name'=> 'Brasil', 'demonym'=> 'brasileño o brasilero']);
		DB::table('countries')->insert(['id'=>218, 'name'=> 'Botsuana', 'demonym'=> 'botsuano']);
		DB::table('countries')->insert(['id'=>219, 'name'=> 'Bosnia y Herzegovina', 'demonym'=> 'bosnio']);
		DB::table('countries')->insert(['id'=>220, 'name'=> 'Bolivia', 'demonym'=> 'boliviano']);
		DB::table('countries')->insert(['id'=>221, 'name'=> 'Bielorrusia', 'demonym'=> 'bielorruso']);
		DB::table('countries')->insert(['id'=>222, 'name'=> 'Bermudas', 'demonym'=> 'bermudeño']);
		DB::table('countries')->insert(['id'=>223, 'name'=> 'Benín', 'demonym'=> 'beninés']);
		DB::table('countries')->insert(['id'=>224, 'name'=> 'Belice', 'demonym'=> 'beliceño']);
		DB::table('countries')->insert(['id'=>225, 'name'=> 'Bélgica', 'demonym'=> 'belga']);
		DB::table('countries')->insert(['id'=>226, 'name'=> 'Baréin', 'demonym'=> 'bareiní']);
		DB::table('countries')->insert(['id'=>227, 'name'=> 'Barbados', 'demonym'=> 'barbadense']);
		DB::table('countries')->insert(['id'=>228, 'name'=> 'Bangladés', 'demonym'=> 'bangladesí']);
		DB::table('countries')->insert(['id'=>229, 'name'=> 'Bahamas', 'demonym'=> 'bahameño']);
		DB::table('countries')->insert(['id'=>230, 'name'=> 'Azerbaiyán', 'demonym'=> 'azerbaiyano']);
		DB::table('countries')->insert(['id'=>231, 'name'=> 'Austria', 'demonym'=> 'austriaco o austríaco']);
		DB::table('countries')->insert(['id'=>232, 'name'=> 'Australia', 'demonym'=> 'australiano']);
		DB::table('countries')->insert(['id'=>233, 'name'=> 'Aruba', 'demonym'=> 'arubeño']);
		DB::table('countries')->insert(['id'=>234, 'name'=> 'Armenia', 'demonym'=> 'armenio']);
		DB::table('countries')->insert(['id'=>236, 'name'=> 'Argelia', 'demonym'=> 'argelino']);
		DB::table('countries')->insert(['id'=>237, 'name'=> 'Arabia Saudita', 'demonym'=> 'saudí o saudita']);
		DB::table('countries')->insert(['id'=>238, 'name'=> 'Antigua y Barbuda', 'demonym'=> 'antiguano']);
		DB::table('countries')->insert(['id'=>239, 'name'=> 'Anguila', 'demonym'=> 'anguilense o anguilano']);
		DB::table('countries')->insert(['id'=>240, 'name'=> 'Angola', 'demonym'=> 'angoleño o angolano']);
		DB::table('countries')->insert(['id'=>241, 'name'=> 'Andorra', 'demonym'=> 'andorrano']);
		DB::table('countries')->insert(['id'=>242, 'name'=> 'Alemania', 'demonym'=> 'alemán']);
		DB::table('countries')->insert(['id'=>243, 'name'=> 'Albania', 'demonym'=> 'albanés']);
		DB::table('countries')->insert(['id'=>244, 'name'=> 'Afganistán', 'demonym'=> 'afgano']);
		DB::table('countries')->insert(['id'=>245, 'name'=> 'Acrotiri y Dhekelia', 'demonym'=> 'acrotirense o anglochipriota']);
    }
}
